name: Github Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
  pull_request:
    branches: 
      - main
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Triggered by ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
      - name: List files in the repo
        run: |
          echo "Repo: ${{ github.repository}} files:"
          tree
